
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/seletivo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: seletivo
    password: seletivo123
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  logging:
    level:
      org.flywaydb: DEBUG

  jpa:
    hibernate:
      ddl-auto: validate